### ISSUE TITLE
Links are repeated twice with different names

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#10]
The three links in the Simulator page of the Familiarization with the UV-Visible Absorption Spectroscopy experiment are same as the three links given under the Familiarization with the UV-Visible Absorption Spectroscopy experiment in the List of Experiment page.
 **In the Simulator page the experiments are given as:** 

![mas-qa-i2](https://cloud.githubusercontent.com/assets/13479177/17356464/05571900-5971-11e6-8512-00cff1b03f70.png)

**In the List Of Experiments page the links are named as below:**

![mas-qa-i3](https://cloud.githubusercontent.com/assets/13479177/17356492/3034be52-5971-11e6-80e4-0992fe0d48fc.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.  Removed the redundant links of the exp1 from experiments list page and modified the links alignment in the exp1 simulator page.

**Comment by BSravanthi** [comment]
Closed #10
