### ISSUE TITLE
QA_MAS_Expt-9_Procedure_Broken tables

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#108]
Defect Description:
The Procedure page of "pH effects on absorption spectra: pKa determination by spectrophotometric method" experiment of this lab, table images are broken. In order to convey the complete information to the user the tables need to be added properly. 

Actual Result :
The Procedure page of "pH effects on absorption spectra: pKa determination by spectrophotometric method" experiment of this lab, table images are broken. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_mas_i25](https://cloud.githubusercontent.com/assets/13479177/22544166/a9904140-e959-11e6-812e-a0bc9a31d721.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed.

**Comment by BSravanthi** [comment]
Closed #108
