### ISSUE TITLE
Name of the experiment differs.

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#11]
The name of the second experiment is given as **Solvent Effects on the UV-visible Absorption Spectra** in all the pages of the experiment. Where as the name of the experiment is **Solvent effects on absorption spectra**

**Comment by sadhanareddy** [comment]
Issue is resolved now.   Corrected the name of the second experiment in list of experiments page from Solvent effects on absorption spectra to "Solvent Effects on the UV-visible Absorption Spectra".

**Comment by BSravanthi** [comment]
Closed #11
