### ISSUE TITLE
Unassigned link in references page

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#12]
In the References page in second experiment in this lab, the link 
http://nsdl.niscair.res.in/bitstream/123456789/793/1/spectroscopy+of+organic+compounds.pdf is not assigned. When I checked this link in the browser the link is redirecting to an error page.

**Comment by sadhanareddy** [comment]
Issue is resolved now.  Disabled the link in exp2/reference page as it is not working and corrected it as link will be updated soon.

**Comment by BSravanthi** [comment]
Closed #12
