### ISSUE TITLE
Name of the experiment differs

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#13]
The third experiment's name of this lab is given as **Sample Path Length Dependence of Absorbance (Lambert Law)** in all the pages of this experiment. Where as the name of the experiment is  **Effects of sample path length**

**Comment by sadhanareddy** [comment]
Issue is resolved.  Corrected the name as  " Effects of sample path length Dependence of Absorbance (Lambert Law) across all the experiment3 pages ".

**Comment by BSravanthi** [comment]
Closed #13
