### ISSUE TITLE
Experiment page redirects to blank 

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#16]
In the  **Effects of sample concentration** experiment, when we click on **Click here to go to lab** link to perform the experiment, the page is redirecting to a blank page.

![mas-qa-i4](https://cloud.githubusercontent.com/assets/13479177/17395323/478053ec-5a47-11e6-92a1-c15b1077cacf.png)

**Comment by sadhanareddy** [comment]
Earlier the experiment was given 3.swf file instead of 4.swf file, due to this experiment is not getting opened.
Anyway converted this experiment simulation to JavaScript.

**Comment by BSravanthi** [comment]
Closed #16
