### ISSUE TITLE
Misposition of the clock's hand

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#20]
In the Simulator page of **pH effects on absorption spectra: pKa determination by spectrophotometric method** experiment, the clock hand's position is not proper, The position should be center of the clock. 

![mas-qa-i6](https://cloud.githubusercontent.com/assets/13479177/17428032/b46972ba-5afe-11e6-9e00-ba8db8e90b5b.png)

**Comment by sadhanareddy** [comment]
issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #20
