### ISSUE TITLE
Measurement Scale needs to be responsive.

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#21]
In the experiment of **pH effects on absorption spectra: pKa determination by spectrophotometric method**, the measurement scale in the simulator is not responsive. When we zoom in or zoom out the position of the scale is changing, where as the size of the scale should change accordingly when we zoom in or zoom out. 

![mas-qa-i7](https://cloud.githubusercontent.com/assets/13479177/17428118/626a447a-5aff-11e6-8bc4-b42a7d146512.png)

**Comment by sadhanareddy** [comment]
issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #21
