### ISSUE TITLE
Font size of the Numbering needs to be proper

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#22]
In the Procedure page of **Study of kinetics of a reaction by using spectrophotometric method** experiment of the Molecular Absorption Spectroscopy Lab, Font size of the numbering is improper. For better look and feel the font size needs to be corrected.

**Comment by sadhanareddy** [comment]
Differing this issue as, the font size in the procedure page is proper.

**Comment by BSravanthi** [comment]
Closed #22
