### ISSUE TITLE
Issue in the Experiment 

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#23]
In the experiment of **Familiarization with the UV-Visible Absorption Spectroscopy** once the solution is poured into the cuvette by the pipette, the pipette should placed back on the table. Where as the pipette is staying back near the experiment desk.

**Comment by sadhanareddy** [comment]
issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #23
