### ISSUE TITLE
The  Solvent effects on absorption spectra experiment is not build properly

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#24]
The Solvent effects on absorption spectra experiment needs to build properly as the positioning of the pipette and other things are not placed properly.

**Comment by sadhanareddy** [comment]
Fixed all the issues in the simulation.

**Comment by BSravanthi** [comment]
Few issues are yet to be fixed. Like cuvette positioning in the spectrometer, the flask can not be moved with out selecting the solvent even if we select.. etc. 
Hence reopening the issue

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #24.
