### ISSUE TITLE
Inconsistency of the data

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#26]
In the procedure page of **pH effects on absorption spectra: pKa determination by spectrophotometric method** experiment in this lab, the table is extended out of the screen and no scroll bar is provided on the down of the screen for the complete visibility of the table. When we zoom out the page, only then the complete table is visible.

**Before Zooming:**

![mas-qa-i9](https://cloud.githubusercontent.com/assets/13479177/17434009/6863d130-5b21-11e6-9c53-a8c8eb7ce1b5.png)

**After Zoom out:**

![mas-qa-i10](https://cloud.githubusercontent.com/assets/13479177/17434019/85f3649a-5b21-11e6-9ba3-7838a0fe4c73.png)

**Comment by sadhanareddy** [comment]
issue is fixed now. Corrected the image size of the table.

**Comment by BSravanthi** [comment]
Closed #26
