### ISSUE TITLE
Identified Inconsistency in the table 

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#27]
In the procedure page of **Effects of sample concentration** experiment in this lab, the table is inconsistent when the page is not zoomed. When we zoom out then the table is visible properly. 

![mas-qa-i8](https://cloud.githubusercontent.com/assets/13479177/17433959/092fe44c-5b21-11e6-9bd2-bb65dfaa0d60.png)

**Comment by sadhanareddy** [comment]
Differring this issue. I didn't find any inconsistency.

**Comment by BSravanthi** [comment]
Closed #27
