### ISSUE TITLE
Jumbled text and Numbering.

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#29]
In the Objective page of the **pH effects on absorption spectra: pKa determination by spectrophotometric method** experiment, numbering got jumbled with the content of the page. 

![mas-qa-i11](https://cloud.githubusercontent.com/assets/13479177/17469386/c85e6ae2-5d4b-11e6-9cff-db0a5c5a492c.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now. Corrected the alignment.

**Comment by BSravanthi** [comment]
Closed #29
