### ISSUE TITLE
Image size needs to be adjusted. 

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#30]
In the Theory page of the experiment **pH effects on absorption spectra: pKa determination by spectrophotometric method**, the image in the page is extended out of the screen. When we shrink the page then we are able to see the whole image. Where as either the page needs to be provided with a horizontal scroll bar or need to decrease the size of the image accordingly with out interrupting the actual font size of the page to maintain the look and feel of the page.

![mas-qa-i12](https://cloud.githubusercontent.com/assets/13479177/17469963/c093c43c-5d51-11e6-8891-b2212ed85077.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #30
