### ISSUE TITLE
Table needs to be inserted in the table format.

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#31]
In the procedure page of the experiment **Verification of Beer-Lambert Law**, instead of giving only table format, table need to be given for the provided data. 

![mas-qa-i13](https://cloud.githubusercontent.com/assets/13479177/17470551/a7ebbb56-5d56-11e6-9df5-37f99c05c8b9.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now. Table format is given.

**Comment by BSravanthi** [comment]
Closed #31
