### ISSUE TITLE
Identified Junk Character

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#32]
In the Procedure page of the experiment **Verification of Beer-Lambert's law**, junk character is present in the middle of the content.

![mas-qa-i14](https://cloud.githubusercontent.com/assets/13479177/17470836/09b02dde-5d59-11e6-91ed-e904408b2633.png)

**Comment by sadhanareddy** [comment]
issue is fixed now. Corrected it as per the instruction given in manual page of the simulation

**Comment by BSravanthi** [comment]
Closed #32
