### ISSUE TITLE
Links given in the reference page needs to be assigned. 

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#33]
The 1st and 2nd links provided in the references page of the **Effects of solution pH on the UV-visible absorption spectra** experiment, are unassigned. Need to assign the links shown in the following screen shot,

![mas-qa-i15](https://cloud.githubusercontent.com/assets/13479177/17471004/46accd36-5d5a-11e6-8827-808fb9f10554.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #33
