### ISSUE TITLE
QA-Effects of solution pH on the UV-visible absorption spectra-Simulation-Naming for the Pipettes

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#35]
**Defect Description** :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, naming for the two pipettes should be given when two different pipettes are present to avoid confusion.

**Actual Result** :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, naming for the two pipettes should be given.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #35
