### ISSUE TITLE
QA-Effects of solution pH on the UV-visible absorption spectra-Simulation-Fix the clock Handle

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#36]
Defect Description :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, the clock handle should be fixed to maintain the perfect positioning of the handle.

Actual Result :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, the clock handle's position is not proper.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #36
