### ISSUE TITLE
QA-Effects of solution pH on the UV-visible absorption spectra-Simulation-Scroll bar for the experiment

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#38]
**Defect Description** :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, A scroll bar needs to be provided to maintain visibility even in the smaller screens.

**Actual Result** :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, Scroll bar is not present to view the entire screen of the experiment.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #38
