### ISSUE TITLE
QA_Effects of solution pH on the UV-visible absorption spectra_Simulation_Reference cuvette image

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#40]
**Defect Description** :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, a reference cuvette's images should be given in order to know which is the reference cuvette.

**Actual Result** :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, no reference cuvette image has been provided.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #40
