### ISSUE TITLE
QA_Effects of solution pH on the UV-visible absorption spectra_Simulation_Slider issue

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#41]
**Defect Description** :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, the slider in the measuring scale should become faded/disabled after selecting beaker, which indicates that the beaker is selected.

**Actual Result** :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, the slider in the measuring scale is not getting faded/disabled after selecting beaker.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #41
