### ISSUE TITLE
QA_Effects of solution pH on the UV-visible absorption spectra_Simulation_Buttons of Spectrometer and Computer

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#42]
**Defect Description** :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, the buttons on the Spectrometer and on the computer needs to be in proper size in order to maintain the look and feel of the page.

**Actual Result** :
In the simulation page of "Effects of solution pH on the UV-visible absorption spectra" experiment, the size of the transparent buttons are not given properly. 

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #42
