### ISSUE TITLE
QA_Determination of unknown concentration of a light absorbing analyte_Simulation

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#45]
**Defect Description** :
In the simulation page of "Determination of unknown concentration of a light absorbing analyte" experiment, when we decrease the window size all the objects in the experiments are adjusting accordingly by moving out of the shelf. Where as all the objects should be stable. The user may use scroll bar in order to view the experiment window when the window size is reduced.

**Actual Result** :
In the simulation page of "Determination of unknown concentration of a light absorbing analyte" experiment, the objects in the experiments are adjusting accordingly by moving out of the shelf.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #45
