### ISSUE TITLE
QA_ Determination of unknown concentration of a light absorbing analyte _Simulation_Buttons in Expt

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#48]
Defect Description :
In the simulation page of " Determination of unknown concentration of a light absorbing analyte " experiment, the buttons on the Spectrometer and on the computer needs to be in proper size in order to maintain the look and feel of the page.

Actual Result :
In the simulation page of " Determination of unknown concentration of a light absorbing analyte " experiment, the size of the transparent buttons are not given properly.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #48
