### ISSUE TITLE
QA_Determination of unknown concentration of a light absorbing analyte_Simulation_issue with slider

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#49]
**Defect Description** :
In the simulation page of "Determination of unknown concentration of a light absorbing analyte" experiment, the slider should be hidden when we select any other/unknown solution.

**Actual Result** :
In the simulation page of "Determination of unknown concentration of a light absorbing analyte" experiment, the slider is not hidden when we select any unknown solution.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #49
