### ISSUE TITLE
QA_ Verification of Beer-Lambert Law_Simulation_graphs

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#50]
**Defect Description**:
The graphs of the experiment are same for all the values in the simulation page of the " Verification of Beer-Lambert Law" experiment. 

**Actual Result**:
For all the values given for the experiment of " Verification of Beer-Lambert Law"  the output graphs are coming same.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
This is the issue in the flash experiment. Hence keeping this issue on hold.
