### ISSUE TITLE
QA_Verification of Beer-Lambert Law_Simulation_Pipette

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#51]
**Defect Description** :
In the simulation page of " Verification of Beer-Lambert Law " experiment, once the solution is poured into the cuvette by pipette, the pipette should be placed back in the shelf. But this is not happening in the experiment.

**Actual Result** :
In the simulation page of " Verification of Beer-Lambert Law " experiment, once the solution is poured into the cuvette with pipette, the pipette is staying back near the experiment table instead of going back to the shelf.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #51
