### ISSUE TITLE
QA_Verification of Beer-Lambert Law_Simulation_Clock handle

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#52]
Defect Description :
In the simulation page of " Verification of Beer-Lambert Law " experiment, the clock handle should be fixed to maintain the perfect positioning of the handle, where as the handle is moving out of the position.

Actual Result :
In the simulation page of " Verification of Beer-Lambert Law " experiment, the clock handle's position is not proper.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #52
