### ISSUE TITLE
QA_Verification of Beer-Lambert Law_Simulation_Color of the solution in conical flask

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#55]
**Defect Description** :
In the simulation page of "Verification of Beer-Lambert Law" experiment, the color of the solution in the conical flask should change according to the the slider's position. Where as in the experiment the color of the solution conical flask is remaining same even after changing the position of the slider.

**Actual Result** :
In the simulation page of **Verification of Beer-Lambert Law** experiment, the color of the solution in the conical flask should change according to the the slider's position. 

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #55
