### ISSUE TITLE
QA_Effects of sample path length Dependence of Absorbance (Lambert Law)_Simulation_misposition of clock Handle

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#56]
**Defect Description** :
In the simulation page of "Effects of sample path length Dependence of Absorbance (Lambert Law)" experiment, the clock handle should be fixed in the middle to maintain the perfect positioning of the handle, where as in this experiment the handle is moving out of the position.

**Actual Result** :
In the simulation page of "Effects of sample path length Dependence of Absorbance (Lambert Law)" experiment, the position clock handle is not properly fixed.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #56
