### ISSUE TITLE
QA_Familiarization with the UV-Visible Absorption Spectroscopy_Simulation_Scroll bar in the experiment

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#65]
**Defect Description** :
In the simulation page of "Familiarization with the UV-Visible Absorption Spectroscopy" experiment, A scroll bar needs to be provided to maintain visibility even the image is bigger than the screen.

**Actual Result** :
In the simulation page of "Familiarization with the UV-Visible Absorption Spectroscopy" experiment, Scroll bar is not present to view the entire screen of the experiment.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #65
