### ISSUE TITLE
QA_Determination of the Molar Absorptivity of a Light Absorbing Molecule_Simulation_Color of the solution

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#66]
**Defect Description** :
In the simulation page of "Determination of the Molar Absorptivity of a Light Absorbing Molecule" experiment, the color of the solution in the conical flask should be yellow. Not orange.

**Actual Result** :
In the simulation page of "Determination of the Molar Absorptivity of a Light Absorbing Molecule" experiment, the color of the solution in the conical flask is orange.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
The color of the solution is still orange.

**Comment by BSravanthi** [comment]
Closed #66
