### ISSUE TITLE
QA_Determination of the Molar Absorptivity of a Light Absorbing Molecule_Simulation_Color of the solution differs

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#67]
**Defect Description** :
In the simulation page of "Determination of the Molar Absorptivity of a Light Absorbing Molecule" experiment, once the solution is poured in the cuvette with the help of the pipette, the color of the solution in that cuvette should match to the color of the solution in the beaker. In this experiment color difference is present between the color of the solutions in cuvette and in the beaker.

**Actual Result** :
In the simulation page of "Determination of the Molar Absorptivity of a Light Absorbing Molecule" experiment, color difference is present between the color of the solutions in cuvette and in the beaker.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #67
