### ISSUE TITLE
QA_Determination of the Molar Absorptivity of a Light Absorbing Molecule_Simulation_scale and slider should be stable

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#69]
**Defect Description** :
In the simulation page of "Determination of the Molar Absorptivity of a Light Absorbing Molecule" experiment, when we change the window size the measurement scale and slider are moving. Where as they should be stable.

**Actual Result** :
In the simulation page of "Determination of the Molar Absorptivity of a Light Absorbing Molecule" experiment, the objects in the experiments are adjusting accordingly by moving out of the shelf.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #69
