### ISSUE TITLE
Name change of the lab

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#7]
Name of the lab In the home page of Molecular Absorption Spectroscopy lab, is given as ABSORPTION SPECTROSCOPY VIRTUAL LAB. Need to change the name of the lab.

**Comment by sadhanareddy** [comment]
Issue is resolved now. Changed the name of the ABSORPTION SPECTROSCOPY VIRTUAL LAB to Molecular Absorption Spectroscopy Lab in all the files of the lab.

**Comment by BSravanthi** [comment]
Closed #7
