### ISSUE TITLE
QA_Effects of sample path length Dependence of Absorbance (Lambert Law)_Simulation_Color of the solution defers

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#74]
**Defect** Description :
In the simulation page of "Effects of sample path length Dependence of Absorbance (Lambert Law)_Simulation" experiment, the color of the solution in the beaker is given wrongly. The color should be yellow.

**Actual Result** :
In the simulation page of "Determination of unknown concentration of a light absorbing analyte" experiment,  the color of the solution in the beaker is given wrongly.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #74
