### ISSUE TITLE
QA_Simultaneous estimation method for multicomponent samples: Principle of additivity of absorbance_simulation_include graphs.

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#83]
**Defect Description** :
In the simulation page of "Simultaneous estimation method for multicomponent samples: Principle of additivity of absorbance" experiment, once the experiment is done we need to click on monitor to view the output. For that graph presentation needs to be there. But the graphs are missing.

**Actual Result** :
In the simulation page of "Simultaneous estimation method for multicomponent samples: Principle of additivity of absorbance" experiment, the graphs are missing to view the output of the experiment.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6 
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #83
