### ISSUE TITLE
QA_Simultaneous estimation method for multicomponent samples: Principle of additivity of absorbance_simulation_Functionality

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#84]
**Defect Description** :
In the simulation page of "Simultaneous estimation method for multicomponent samples: Principle of additivity of absorbance" experiment, the functionality of the drop down menu and measuring scale should be appropriate.

**Actual Result** :
In the simulation page of "Simultaneous estimation method for multicomponent samples: Principle of additivity of absorbance" experiment, the functionality of the drop down menu and measuring scale are deferring.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Close #84
