### ISSUE TITLE
QA_Familiarization with the UV-Visible Absorption Spectroscopy_Simulation_Cuvette position

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#85]
**Defect Description** :
In the simulation page of "Familiarization with the UV-Visible Absorption Spectroscopy" experiment, the functionality of the cuvette and reference cuvette is improper. The cuvette and reference cuvette should be placed in its position of the spectrometer. Where as the positioning is improper.

**Actual Result** :
In the simulation page of "Familiarization with the UV-Visible Absorption Spectroscopy" experiment, the functionality of the cuvette and reference cuvette is improper. 

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_mas_i1](https://cloud.githubusercontent.com/assets/13479177/18383816/b8876e7a-76a0-11e6-82f9-b6bc03293e07.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #85
