### ISSUE TITLE
QA_Determination of the Molar Absorptivity of a Light Absorbing Molecule_Simulation_Measuring scale

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#86]
**Defect Description** :
In the simulation page of "Determination of the Molar Absorptivity of a Light Absorbing Molecule" experiment, the functionality of the measuring scale is not appropriate. The color/concentration of the solution in the flask should change according to the movement of the scale. Where as the color/concentration is remaining same even when we move the scale.

**Actual Result** :
In the simulation page of "Determination of the Molar Absorptivity of a Light Absorbing Molecule" experiment, the functionality of the measuring scale is not appropriate. The color/concentration is remaining same even when we move the scale.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_mas_i2](https://cloud.githubusercontent.com/assets/13479177/18384296/315ae140-76a3-11e6-9ee8-8ecff07cf461.png)

**Comment by sadhanareddy** [comment]
In the existing flash experiment, colour of the flask remain same, when the slider of the scale is moved. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #86
