### ISSUE TITLE
QA_Determination of the Molar Absorptivity of a Light Absorbing Molecule_Simulation_Cuvette position

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#87]
**Defect Description** :
In the simulation page of "Determination of the Molar Absorptivity of a Light Absorbing Molecule" experiment, the functionality of the cuvette and reference cuvette is improper. The cuvette and reference cuvette should be placed in its position of the spectrometer. Where as the positioning is improper.

**Actual Result** :
In the simulation page of "Determination of the Molar Absorptivity of a Light Absorbing Molecule" experiment, the functionality of the cuvette and reference cuvette is improper.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_mas_i3](https://cloud.githubusercontent.com/assets/13479177/18384389/ae78d434-76a3-11e6-8a1a-a52339e2d46b.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #87
