### ISSUE TITLE
QA_Simultaneous estimation method for multicomponent samples: Principle of additivity of absorbance_Simulation

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#88]
**Defect Description** :
In the simulation page of "Simultaneous estimation method for multicomponent samples: Principle of additivity of absorbance" experiment, when we select **Coumarin6** from the drop down menu.. Earlier the color of the solution in the flask was Orange, while pouring the solution from flask to beaker color of the solution is changing from Orange to gray. Where as the color should be remained same even after pouring the solution. 

**Actual Result** :
In the simulation page of "Simultaneous estimation method for multicomponent samples: Principle of additivity of absorbance" experiment, when we select **Coumarin6** from the drop down menu.. Earlier the color of the solution in the flask was Orange, while pouring the solution from flask to beaker color of the solution is changing from Orange to gray.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
Screen shot before pouring:
![qa_mas_i6](https://cloud.githubusercontent.com/assets/13479177/18386396/3af6a704-76b0-11e6-95e0-ad505159b6ed.png)

Screen shot after pouring:
![qa_mas_i5](https://cloud.githubusercontent.com/assets/13479177/18386373/1cebb132-76b0-11e6-8678-e2688f4b1be5.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #88
