### ISSUE TITLE
QA_Molecular Absorption Spectroscopy Lab_all experiments_cursor

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#89]
Defect Description :
In all the simulations of "Molecular Fluorescence Spectroscopy Lab", the cursor is changing for all the objects instead, the mouse pointer should be changed according to the process of the experiment. According to the simulation process the mouse pointer should change on the desired object. But in all the experiments of this lab irrespective of the procedure the mouse pointer is getting changed to the cursor for all the objects.

Actual Result :
In all the simulations of "Molecular Fluorescence Spectroscopy Lab", the cursor is changing for all the objects instead, the mouse pointer should be changed according to the process of the experiment. According to the simulation process the mouse pointer should change on the desired object. But in all the experiments of this lab irrespective of the procedure the mouse pointer is getting changed to the cursor for all the objects.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_mas_i7](https://cloud.githubusercontent.com/assets/13479177/21258842/df7f70d0-c3a4-11e6-90cc-8844db3a8e7f.png)

**Comment by sadhanareddy** [comment]
Issue is fixed.

**Comment by BSravanthi** [comment]
Except in 9th simulation in all the other other experiments the issue is fixed. Hence reopening the issue.
In 9th experiment the mouse pointer is changing to cursor when we place it on the slider bar even when undesired.

**Comment by sadhanareddy** [comment]
Issue is fixed

**Comment by BSravanthi** [comment]
Closed #89
