### ISSUE TITLE
Improper alignment in Familiarization with the UV-Visible Absorption Spectroscopy experiment

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#9]
In the Quiz page of the Familiarization with the UV-Visible Absorption Spectroscopy experiment of this lab, need to correct the alignment to maintain the look and feel of the page. 

![mas-qa-i1](https://cloud.githubusercontent.com/assets/13479177/17356073/a609d32c-596e-11e6-8187-b8609aee040c.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.  Corrected the alignment of the Quiz page.

**Comment by BSravanthi** [comment]
Closed #9
