### ISSUE TITLE
QA_Molecular Absorption Spectroscopy Lab_all experiments_Animation distortions

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#90]
Defect Description :
In all the experiments of "Molecular Absorption Spectroscopy Lab" When animation is going on an 'x' element, if we click on an other element to animate, the current animation is getting stopped in the middle and creating position distortions in the experiment. Due to this whole experiment functionality is getting disturbed.

Actual Result :
In all the experiments of "Molecular Absorption Spectroscopy Lab" When animation is going on an 'x' element, if we click on an other element to animate, the current animation is getting stopped in the middle and creating position distortions in the experiment. Due to this whole experiment functionality is getting disturbed.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_mas_i8](https://cloud.githubusercontent.com/assets/13479177/21259221/7fbd8216-c3a6-11e6-9be0-3eec411f7d3a.png)

**Comment by sadhanareddy** [comment]
Issue is fixed.

**Comment by BSravanthi** [comment]
Closed #90
