### ISSUE TITLE
QA_Molecular Absorption Spectroscopy Lab_Effects of solution pH on the UV-visible absorption spectra_Simulation_color of the solution in the covette

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#91]
Defect Description :
In the "Effects of solution pH on the UV-visible absorption spectra" experiment of this lab, when we change the concentration of the covette's solution using the slider bar, the color of the solution is remaining same. Where as the color of the solution should be changed according to the concentration level.

Actual Result :
In the "Effects of solution pH on the UV-visible absorption spectra" experiment of this lab, when we change the concentration of the covette's solution using the slider bar, the color of the solution is remaining same. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_mas_i9 i](https://cloud.githubusercontent.com/assets/13479177/21384185/732bddbc-c78f-11e6-9066-75e9367fc117.png)
![qa_mas_i9 ii](https://cloud.githubusercontent.com/assets/13479177/21384186/732e9f02-c78f-11e6-88fa-5500265f3173.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed.

**Comment by BSravanthi** [comment]
Need to fix the cursor issue which is not changing when it is placed on slider but changing when placed on the scale.  Hence reopened the issue.

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #91
