### ISSUE TITLE
QA_Molecular Absorption Spectroscopy Lab_all experiments_Image distortions

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#92]
Defect Description :
In all the experiment of this lab, when table slot is getting changed it is creating blinking effect due to the width of the image. 

Actual Result :
In all the experiment of this lab, when table slot is getting changed it is creating blinking effect due to the width of the image. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:

**Comment by sravanthimodepu** [comment]
Issue is fixed.

**Comment by BSravanthi** [comment]
Closed #92
